### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by c1sxr0bzn** [riking/AutoDelete#43]
When trying to add the bot to a server, Discord will show this message.

![image](https://user-images.githubusercontent.com/98315842/168472643-e46cd71a-eee0-47f3-8816-91191ed3f9c4.png)

**Comment by c1sxr0bzn** [comment]
Project seems dead, but anyways, error can be bypassed by using:
https://discordapi.com/permissions.html

**Comment by MeesJ** [comment]
I came across your issue because I had the same issue, and I found how to solve it. Sharing it here for future reference.

To ensure Discord's OAuth2 doesn't throw that error, you need to put your redirect URI in your application's settings, right here:
![](https://user-images.githubusercontent.com/77725857/222199472-ba8a645f-93ce-4dfb-97e5-cf6775950b5f.png)
